[2021-01-06T16:20:32.118] [ERROR] error - 
  ReferenceError: fields is not defined
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:19:9)
      at dispatch (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
      at next (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
      at D:\fitmgr\otherweb\worktask\server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
      at dispatch (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
      at D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
      at dispatch (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
      at dispatch (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
      at allowedMethods (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:407:12)
      at dispatch (D:\fitmgr\otherweb\worktask\server\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)

[2021-01-06T16:21:31.696] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:09:41.358] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:12:42.918] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:17:36.106] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:19:09.462] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:19:24.619] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:25:14.242] [ERROR] error - 
  Error: ER_PARSE_ERROR: 
      at Query.Sequence._packetToError (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      --------------------
      at Protocol._enqueue (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
      at pool.getConnection (D:\fitmgr\otherweb\worktask\server\pool.js:21:20)
      at Ping.onOperationComplete (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
      at Ping._callback (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:488:16)
      at Ping.Sequence.end (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (D:\fitmgr\otherweb\worktask\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)

[2021-01-06T22:52:08.476] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:107:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T22:52:42.288] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:108:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T22:56:39.102] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:108:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T22:57:18.183] [ERROR] error - 
  ReferenceError: evel is not defined
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:106:25)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T22:57:42.536] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:108:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T22:59:55.255] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:109:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T23:01:22.205] [ERROR] error - 
  TypeError: curRemark.push is not a function
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:109:19)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-06T23:04:05.584] [ERROR] error - 
  SyntaxError: Unexpected token ' in JSON at position 0
      at JSON.parse (<anonymous>)
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\demand.js:106:30)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-13T15:34:41.571] [ERROR] error - 
  Error: ENOENT: no such file or directory, open '..\template\index.vue'
      at Object.fs.openSync (fs.js:545:3)
      at Object.fs.readFileSync (fs.js:451:33)
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\server.config.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-13T15:35:35.863] [ERROR] error - 
  Error: ENOENT: no such file or directory, open '..\template\index.vue'
      at Object.fs.openSync (fs.js:545:3)
      at Object.fs.readFileSync (fs.js:451:33)
      at router.post (D:\fitmgr\otherweb\worktask\server\routes\server.config.js:82:24)
      at process._tickCallback (internal/process/next_tick.js:178:7)

[2021-01-13T15:40:02.368] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T15:46:22.064] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T15:47:14.671] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T15:49:51.854] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:14:07.327] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:16:16.360] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:26:38.131] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:30:30.921] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:36:07.249] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:36:39.690] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:37:04.427] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:37:09.504] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:38:46.811] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:52:11.581] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:53:42.455] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:55:10.887] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T16:57:41.354] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:00:40.279] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:02:32.064] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:03:14.666] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:05:59.328] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:06:36.763] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:08:41.933] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:18:56.248] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:24:05.068] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:26:40.476] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:38:03.416] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:40:38.287] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
[2021-01-13T17:43:10.207] [ERROR] error - error!
D:\fitmgr\otherweb\worktask\server\template\target\conversation\index.vue has already been existed!
